import numpy as np
import pandas as pd
from transformers import BertTokenizer, BertForSequenceClassification
import torch
import joblib
from pdf import createPDF
from extract import extract_text

def Plagarism_check(file_path,hmm_model,tokenizer,model):



    def sentence_lengths(text):
        return np.array([len(sentence.split()) for sentence in text.split('.') if sentence])


    def classify_with_segments(text, segments):
        tokens = tokenizer(text, truncation=True, padding=True, return_tensors="pt")
        output = model(**tokens)
        predictions = torch.argmax(output.logits, dim=1).item()
        return predictions


    def predict_author(text):
      # Preprocess: Extract sentence lengths for HMM segmentation
      sentence_lens = sentence_lengths(text)
      if sentence_lens.shape[0] > 0:
        # Predict segments using HMM
        segments = hmm_model.predict(sentence_lens.reshape(-1, 1))

        # Classify using BERT with segments
        prediction = classify_with_segments(text, segments)


        return prediction
      else:
        return 2 
      
    AI_text = 0
    human_text = 0

    text = extract_text(file_path)
    pdf = createPDF('result.pdf')
    pdf.add_cover_page()
    for i in text:
      new_text = i
      prediction = predict_author(new_text)

      if prediction == 0:
        pdf.add_text(new_text,"human")
        human_text+=len(new_text)
        print("Human")
      elif prediction ==2:
        print("Invalid Text")
      else:
        pdf.add_text(new_text,"AI")
        AI_text+=len(new_text)
        print("AI generated")
      
    total_text = AI_text+human_text
    AI_percent = (AI_text/total_text)*100
    print('\n')
    print(' '*35,"*"*50)
    print(' '*40,f"{AI_percent:.2f}% text is likely generated by AI")
    print(' '*35,"*"*50)
    print('\n')
    pdf.save_pdf()

    
    return AI_percent


if __name__ == '__main__':
   Plagarism_check()